acc_valid: 0.0
batch_size: 1
epochs: 1
eps: 1
eps_valid: 3
gate: input
gate_bias: false
gpu: '1'
gpus: '1'
layer_pred: -1
learning_rate: 0.0003
learning_rate_alpha: 0.3
learning_rate_placeholder: 0.001
model_path: /data/tanhexiang/CF_QA/models/reader/nq_reader_base
n_context: 100
passage_len: 200
passages_source_path: /data/tanhexiang/CF_QA/data/wikipedia_split/psgs_w100.tsv
placeholder: true
seed: 0
target_len: 20
train_filename: /data/tanhexiang/tevatron/tevatron/data_nq/result100/fid.nq.small.jsonl
val_filename: /data/tanhexiang/tevatron/tevatron/data_nq/result100/fid.nq.small.jsonl
